SCALE = 4

SCREEN_RES_WIDTH = 1920
SCREEN_RES_HEIGHT = 1080

X_TILE_COUNT = 18
Y_TILE_COUNT = 10

SCREEN_WIDTH = 16*SCALE*X_TILE_COUNT
SCREEN_HEIGHT = 16*SCALE*Y_TILE_COUNT

TEXTURE = 0
OIRAM = 1
OVERWORLDMAP = 2

SPRITE_LIST = ["basicTiles_16_16.png", "smallOiram_16_16.png", "worldmapsprites_32_32.png"]

MAP_WIDTH = 16
MAP_HEIGHT = 16
MAP = "overworld.png"

#TEXTURES
GRASSDIRT = 0
DIRT = 1
GRASS = 2
SKY = 3
POWERUP = 4
POWERUP_SHINE = 5
BLOCK = 9
BLOCK_PUSH = 9
BRICK = 11
BRICK_UNDERWORLD = 18
STONE = 19
STONE_UNDERWORLD = 20
COIN_STILL = 21
COIN_UNDERWORLD_STILL = 22
COIN_FLIP_ANIMATION = 23
COIN_UNDERWORLD_FLIP_ANIMATION = 28
SHROOM = 33
SHROOM_HP = 35
FLOWER = 36
STAR = 39

H_ROAD = 0
V_ROAD = 1
BG = 2
TREE = 3
CLOSED_DOOR = 4
OPEN_DOOR = 5
COMPLETE_DOOR = 6
MINI_BOSS = 7
BOSS = 8