SCALE = 4

SCREEN_RES_WIDTH = 1920
SCREEN_RES_HEIGHT = 1080

X_TILE_COUNT = 18
Y_TILE_COUNT = 10

SCREEN_WIDTH = 16*SCALE*X_TILE_COUNT
SCREEN_HEIGHT = 16*SCALE*Y_TILE_COUNT

TEXTURE = 0
OIRAM = 1
OVERWORLDMAP = 2

SPRITE_LIST = ["basicTiles_16_16.png", "smallOiram_16_16.png", "worldmapsprites_32_32.png"]

LEVELS = [None]*16*16
LEVELS[0] = "level3.png"
LEVELS[1] = (0,1)
MAP = "overworld.png"


#TEXTURES
GRASSDIRT = 0
DIRT = 1
GRASS = 2
SKY = 3
POWERUP = 4
POWERUP_used = 5
POWERUP_dark = 6
POWERUP_darker = 7
BLOCK = 8
BRICK = 9
BRICK_UNDERWORLD = 10
STONE = 11
STONE_UNDERWORLD = 12
COIN_STILL = 13
COIN_UNDERWORLD_STILL = 14
COIN_FLIP_ANIMATION = 15
COIN_UNDERWORLD_FLIP_ANIMATION = 20
SHROOM = 25
SHROOM_HP = 27
FLOWER = 29

H_ROAD = 0
L_ROAD = 1
BG = 2
TREE = 3
CLOSED_DOOR = 4
OPEM_DOOR = 5
COMPLETE_DOOR = 6
MINI_BOSS = 7
BOSS = 8